// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Tim Backend",
            "email": "support@prestasi.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/achievements": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat seluruh prestasi yang masuk (Admin Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Dosen \u0026 Admin)"
                ],
                "summary": "List ALL Prestasi (Admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AchievementReference"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mahasiswa mengupload data prestasi (Draft). File upload wajib via form-data.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Mahasiswa)"
                ],
                "summary": "Upload Prestasi Baru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Judul Prestasi",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tipe: Kompetisi / Organisasi",
                        "name": "achievement_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tanggal (YYYY-MM-DD)",
                        "name": "event_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Bukti Lampiran (PDF/IMG)",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/achievements/advisees": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat daftar prestasi mahasiswa bimbingan (Dosen Wali Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Dosen \u0026 Admin)"
                ],
                "summary": "List Prestasi Bimbingan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AchievementReference"
                            }
                        }
                    }
                }
            }
        },
        "/achievements/my": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat daftar prestasi milik mahasiswa yang sedang login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Mahasiswa)"
                ],
                "summary": "List Prestasi Saya",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AchievementReference"
                            }
                        }
                    }
                }
            }
        },
        "/achievements/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat detail lengkap prestasi (termasuk data MongoDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Common)"
                ],
                "summary": "Detail Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AchievementReference"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah data prestasi (Hanya jika status Draft)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Mahasiswa)"
                ],
                "summary": "Update Data Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Judul Prestasi",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Update File (Optional)",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus (Soft Delete) prestasi yang masih draft",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Mahasiswa)"
                ],
                "summary": "Delete Prestasi (Draft)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/achievements/{id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat jejak status (Draft -\u003e Submitted -\u003e Verified)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Common)"
                ],
                "summary": "History Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/achievements/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menolak prestasi dengan catatan (Status -\u003e Rejected)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Dosen \u0026 Admin)"
                ],
                "summary": "Reject Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field: notes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/achievements/{id}/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah status Draft menjadi Submitted (Siap Diverifikasi)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Mahasiswa)"
                ],
                "summary": "Submit Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/achievements/{id}/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyetujui prestasi (Status -\u003e Verified)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements (Dosen \u0026 Admin)"
                ],
                "summary": "Verify Prestasi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Achievement Ref ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Masuk ke sistem untuk mendapatkan Token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Username \u0026 Password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat data diri user yang sedang login (Butuh Token)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/lecturers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat daftar dosen",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relations (Admin)"
                ],
                "summary": "List Lecturers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LecturerResponse"
                            }
                        }
                    }
                }
            }
        },
        "/reports/statistics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat total user dan statistik prestasi (Admin Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports (Admin)"
                ],
                "summary": "Dashboard Statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/student/{studentID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat laporan/transkrip prestasi lengkap mahasiswa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports (Admin)"
                ],
                "summary": "Student Transcript",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Tabel Students (UUID)",
                        "name": "studentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentReportResponse"
                        }
                    }
                }
            }
        },
        "/students": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat daftar mahasiswa beserta dosen walinya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relations (Admin)"
                ],
                "summary": "List Students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/students/{id}/advisor": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghubungkan mahasiswa dengan dosen wali",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relations (Admin)"
                ],
                "summary": "Assign Dosen Wali",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Advisor ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AssignAdvisorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat semua user di sistem (Admin Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "List All Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        },
        "/users/lecturers": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendaftarkan akun baru untuk Dosen (Admin Only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Register Dosen",
                "parameters": [
                    {
                        "description": "Data Dosen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateLecturerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/students": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendaftarkan akun baru untuk Mahasiswa (Admin Only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Register Mahasiswa",
                "parameters": [
                    {
                        "description": "Data Mahasiswa",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat detail user berdasarkan ID (Admin Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Get User Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah data dasar user (Admin Only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field: full_name, username, email",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus user dan profil terkait (Admin Only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengganti password user lain (Admin Only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users (Admin)"
                ],
                "summary": "Reset Password User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field: password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AchievementDetails": {
            "type": "object",
            "properties": {
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "certification_name": {
                    "description": "--- Certification (NEW - Sesuai SRS) ---",
                    "type": "string"
                },
                "certification_number": {
                    "type": "string"
                },
                "competition_level": {
                    "type": "string"
                },
                "competition_name": {
                    "description": "--- Competition ---",
                    "type": "string"
                },
                "custom_fields": {
                    "description": "--- Dynamic Extension (NEW - Sesuai SRS) ---\nMenampung field lain yang tidak terdefinisi (SRS: customFields?: Object)",
                    "type": "object",
                    "additionalProperties": true
                },
                "end_date": {
                    "type": "string"
                },
                "event_date": {
                    "description": "--- General ---",
                    "type": "string"
                },
                "issn": {
                    "type": "string"
                },
                "issued_by": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "medal_type": {
                    "type": "string"
                },
                "organization_name": {
                    "description": "--- Organization ---",
                    "type": "string"
                },
                "organizer": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "publication_title": {
                    "type": "string"
                },
                "publication_type": {
                    "description": "--- Publication (NEW - Sesuai SRS) ---",
                    "type": "string"
                },
                "publisher": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "description": "NEW",
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "models.AchievementMongo": {
            "type": "object",
            "properties": {
                "achievement_type": {
                    "type": "string"
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Attachment"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "details": {
                    "$ref": "#/definitions/models.AchievementDetails"
                },
                "id": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "student_id": {
                    "description": "Disimpan sebagai string UUID",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.AchievementReference": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "detail": {
                    "description": "Field ini diisi setelah menggabungkan data dengan MongoDB di Service layer",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AchievementMongo"
                        }
                    ]
                },
                "id": {
                    "description": "UUID dari Postgres",
                    "type": "string"
                },
                "mongo_achievement_id": {
                    "type": "string"
                },
                "rejection_note": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "verified_at": {
                    "type": "string"
                }
            }
        },
        "models.AchievementReportItem": {
            "type": "object",
            "properties": {
                "event_date": {
                    "description": "Dari Mongo Details",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "Kompetisi/Organisasi",
                    "type": "string"
                },
                "verified_at": {
                    "type": "string"
                }
            }
        },
        "models.AssignAdvisorRequest": {
            "type": "object",
            "required": [
                "advisor_id"
            ],
            "properties": {
                "advisor_id": {
                    "description": "ID tabel Lecturers",
                    "type": "string"
                }
            }
        },
        "models.Attachment": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_type": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "string"
                }
            }
        },
        "models.CreateLecturerRequest": {
            "type": "object",
            "required": [
                "department",
                "email",
                "full_name",
                "lecturer_id",
                "password",
                "username"
            ],
            "properties": {
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "lecturer_id": {
                    "description": "Data khusus tabel lecturers",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.CreateStudentRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "email",
                "full_name",
                "password",
                "program_study",
                "student_id",
                "username"
            ],
            "properties": {
                "academic_year": {
                    "type": "string"
                },
                "advisor_id": {
                    "description": "AdvisorID adalah ID dari Dosen Wali (UUID dari tabel lecturers)",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "program_study": {
                    "type": "string"
                },
                "student_id": {
                    "description": "Data khusus tabel students",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.LecturerResponse": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "full_name": {
                    "description": "Dari tabel Users",
                    "type": "string"
                },
                "id": {
                    "description": "ID tabel Lecturers (UUID)",
                    "type": "string"
                },
                "lecturer_id": {
                    "description": "Dari tabel Lecturers",
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ReportSummary": {
            "type": "object",
            "properties": {
                "total_entries": {
                    "type": "integer"
                },
                "total_points": {
                    "description": "Opsional: Jika nanti ada sistem poin SKP",
                    "type": "integer"
                },
                "total_verified": {
                    "type": "integer"
                }
            }
        },
        "models.StudentHeader": {
            "type": "object",
            "properties": {
                "advisor_name": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "program_study": {
                    "type": "string"
                },
                "student_id": {
                    "description": "NIM",
                    "type": "string"
                }
            }
        },
        "models.StudentReportResponse": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AchievementReportItem"
                    }
                },
                "student_info": {
                    "$ref": "#/definitions/models.StudentHeader"
                },
                "summary": {
                    "$ref": "#/definitions/models.ReportSummary"
                }
            }
        },
        "models.StudentResponse": {
            "type": "object",
            "properties": {
                "advisor_name": {
                    "description": "Nama Dosen Wali",
                    "type": "string"
                },
                "full_name": {
                    "description": "Dari tabel Users",
                    "type": "string"
                },
                "id": {
                    "description": "ID tabel Students (UUID)",
                    "type": "string"
                },
                "program_study": {
                    "type": "string"
                },
                "student_id": {
                    "description": "Dari tabel Students",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "role_id": {
                    "type": "string"
                },
                "role_name": {
                    "description": "Relasi (Optional, diisi jika join)",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: Bearer \u003ctoken_jwt_anda\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sistem Pelaporan Prestasi Mahasiswa API",
	Description:      "API untuk sistem prestasi mahasiswa (PostgreSQL + MongoDB).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
